<?php

/**
 * @file
 * Contains advanced_search_tips.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function advanced_search_tips_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the advanced_search_tips module.
    case 'help.page.advanced_search_tips':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function advanced_search_tips_theme() {
  return [
    'advanced_search_tips' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_install().
 */
function advanced_search_tips_install() {
    // Remove existed configuration of structure_sync.data
    \Drupal::configFactory()->getEditable('structure_sync.data')->delete();

    // Clone the Site Help page from https://memory.digital.utsc.utoronto.ca/site-help
    $doc = new \DOMDocument();
    $doc->validateOnParse = true;
    $doc->loadHtml(file_get_contents('https://memory.digital.utsc.utoronto.ca/site-help'));

    // Get the html content of the page in Memory site
    $body = DOMinnerHTML($doc->getElementById('block-barriodepartments-content'));
    $body = str_replace("/sites/default/files", "https://memory.digital.utsc.utoronto.ca/sites/default/files", $body);
    // Create node wth the content.
    $node = Node::create([
      'type' => 'page',
      'title' => 'Site Help',
    ]);
    $node->set('body', $body);
    $node->body->format = 'full_html';
    $node->save();
}

/**
 * Get InnerHTML of an element
 * @param DOMNode $element
 * @return string
 */
function DOMinnerHTML(DOMNode $element) {
  $innerHTML = "";
  $children = $element->childNodes;

  foreach ($children as $child) {
    $innerHTML .= $element->ownerDocument->saveHTML($child);
  }

  return $innerHTML;
}

