<?php

/**
 * @file
 * Contains advanced_search_tips.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function advanced_search_tips_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the advanced_search_tips module.
    case 'help.page.advanced_search_tips':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function advanced_search_tips_theme() {
  return [
    'advanced_search_tips' => [
      'render element' => 'children',
    ],
  ];
}
